#Overwritten on 1758914243775
#Fri Sep 26 15:17:23 EDT 2025
milvus.collection.name=test_collection_from_file
milvus.dimension=384
milvus.host=localhost
milvus.password=
milvus.port=37951
milvus.token=dummy_token_for_testing
milvus.uri=http\://localhost\:37951
milvus.username=
