#Overwritten on 1760471247004
#Tue Oct 14 15:47:27 EDT 2025
milvus.password=
milvus.uri=http\://localhost\:44891
milvus.username=
milvus.dimension=384
milvus.port=44891
milvus.host=localhost
milvus.token=dummy_token_for_testing
milvus.collection.name=test_collection_from_file
